### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by gartesa**
Paso 1 Dockerfile.

### CODE REVIEW

**Comment by Joffcom** [comment]
@gartesa can you clarify what you are actually doing in this PR?

**Comment by gartesa** [comment]
Estoy intentando que mi n8n funcione bajo Docker.
Gracias.

**Comment by Joffcom** [comment]
@gartesa sorry we are only able to provide support in English but if you are trying to get your n8n working in docker I don't think we need it as a PR for this repo. Did you mean to submit it on the main template repo?

**Comment by netroy** [comment]
No hay ningún `npm start` en este proyecto (n8n-nodes-starter) y no hay necesidad de un Dockerfile.

**Comment by netroy** [comment]
I believe you are looking for the n8n main repository, which is [here](https://github.com/n8n-io/n8n), and has a devcontainers setup already included. So, you should be able to use it with codespaces.

**Pull request closed without merging**
