### PR TITLE
stop using n8n-core in nodes

### PR DESCRIPTION
**Pull request by netroy**
This should hopefully fix https://community.n8n.io/t/custom-node-creation-error/40783

### CODE REVIEW

**Review by Joffcom — APPROVED** [review]

**Comment by aminebeh** [comment]
Hi @netroy,

First I want to thanks you for your works 🙏 

I tried to develop my first custom nodes, and it seems that the [documentation](https://docs.n8n.io/integrations/creating-nodes/build/programmatic-style-node/#step-31-imports) is outdated.

Maybe that's why people keep using `n8n-core` to answer your question in [this post](https://community.n8n.io/t/custom-node-creation-error/40783/30) on the community forum.

Is there a plan to update the documentation ?

Thanks in advance !

**Comment by netroy** [comment]
@aminebeh Thanks for pointing that out.
I've opened a [PR](https://github.com/n8n-io/n8n-docs/pull/2609) to get these updated.

**Comment by mathisgauthey** [comment]
Excuses me if this is inappropriate to message on a merged PR, but how can I make the `credentialTest` work on a custom node if `n8n-core` dependency is removed ?

Based on the posts I found : 
- [n8n node development: "No testing function found for this credential."](https://stackoverflow.com/questions/75109822/n8n-node-development-no-testing-function-found-for-this-credential)
- https://community.n8n.io/t/couldn-t-connect-with-these-settings-no-testing-function-found-for-this-credential/33558/2
- https://github.com/n8n-io/n8n/issues/8188
- https://github.com/n8n-io/n8n/pull/11329

The solution I figured was to add "n8n-core" as a devDependency for build and modify the build script from `tsc && gulp build:icons` to `tsc && gulp build:icons && pnpm n8n-generate-metadata`

Thanks in advance, hope you can redirect me to the correct solution.

**Comment by netroy** [comment]
> how can I make the `credentialTest` work on a custom node if `n8n-core` dependency is removed

I don't think you should need `n8n-core` for `credentialTest`. Do you have any publicly available repo where you are seeing this issue? Perhaps there is a bug that we need to fix.

**Comment by mathisgauthey** [comment]
> > how can I make the `credentialTest` work on a custom node if `n8n-core` dependency is removed
> 
> I don't think you should need `n8n-core` for `credentialTest`. Do you have any publicly available repo where you are seeing this issue? Perhaps there is a bug that we need to fix.

Hey there, I think that [this repo](https://github.com/NguyeNgocPhus/n8n-test-node) from [this community post](https://community.n8n.io/t/couldn-t-connect-with-these-settings-no-testing-function-found-for-this-credential/33558/4) would be a good starting point. It has the same setup that I'm using, yet the credentialTest is never called.

**Pull request merged**
